require("dotenv").config();
const {APP_PORT,MONGOOSE_CONNECTION_STRING,ACCESS_KEY,SECRET_ACCESS_KEY,BUCKET,REGION,s3,ADMIN_KEY}=process.env;
module.exports={APP_PORT,MONGOOSE_CONNECTION_STRING,ACCESS_KEY,SECRET_ACCESS_KEY,BUCKET,REGION,s3,ADMIN_KEY};